name: CanExClasif
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - opencv=4.12.0
  - numpy=2.3.1
  - scipy=1.15.3
  - scikit-image=0.25.2
  - scikit-learn=1.7.0
  - matplotlib=3.10.3
  - pandas=2.3.0
  - tqdm=4.67.1
  - ruptures=1.1.9            # Change point detection
  - jupyterlab=4.4.4          # For experimentation and visualization
  - ipykernel=6.29.5